config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :meetups do
    resources :comments
  end

  root 'meetups#index'
  #root "welcome#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def new
    @comment = Comment.new
  end

  def create
    @meetup = Meetup.find(params[:meetup_id])

    @comment = Comment.new(comment_params)
    @comment.meetup_id = @meetup.id
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to :back
    else
      render :new
    end
  end


  protected
  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
  before_action :authenticate_user! , only: [:new, :create, :edit, :update, :destroy]
  before_action :find_meetup_and_check_permission, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @meetups = Meetup.all
  end

  def show
    @meetup = Meetup.find(params[:id])
  end

  def edit
  end

  def new
    @meetup = Meetup.new
  end

  def update
    if  @meetup.update(meetup_params)
      redirect_to meetups_path, natice: "Update success ."
    else
      render :edit
    end
  end

  def create
    @meetup = Meetup.new(meetup_params)
    @meetup.user = current_user
    if @meetup.save
      redirect_to meetups_path, notice: "Create success ."
    else
      render :new
    end
  end

  def destroy
    @meetup.destroy
    redirect_to meetups_path, alert: "Meetup deleted ."
  end

  def find_meetup_and_check_permission
    @meetup = Meetup.find(params[:id])

    if current_user != @meetup.user
      redirect_to root_path, alert: "You have no permission."
    end
  end

  private

  def meetup_params
    params.require(:meetup).permit(:title, :description)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "早安！你好！"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment_form.html.erb
<%= simple_form_for(Comment.new, url: meetup_comments_path(@meetup)) do |f| %>
  <div class="form-group">
    <%= f.text_area :message %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>





<% end %>

app/views/comments/_comment_html.html.erb
<div class="comments">
  <p><strong><%= @comment.name %></strong></p>
  <p><%= comment.body %></p>
  <p><%= time_ago_in_words(comment.created_at) %>Ago</p>

  <p><%= link_to 'Delete', [comment.meetup, comment],
                  method: :delete,
                  class: "button",
                  data: { confirm: 'Are you sure?' } %></p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@meetup, @meetup.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %><br>
  </p>
  <p>
  <%= f.submit %><br>
  </p>

<% end %>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 Rails101
        <br>Design by
        <a href="#" target=_new>qiaoyu</a>
    </p>
</footer>
<!-- 以上部分，不需要记忆 -->

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Rails 101</a>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <% if !current_user %>
                  <li><%= link_to("注册", new_user_registration_path) %> </li>
                  <li><%= link_to("登录", new_user_session_path) %></li>
                <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!, <%= current_user.email %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li> <%= link_to("退出", destroy_user_session_path, method: :delete) %> </li>
                    </ul>
                  </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>
<!-- 以上部分，不需要记忆 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MEETUP</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

        <div class="container-fluid">
          <div class="row">
            <%= render "common/navbar" %>
            <%= render "common/flashes" %>
          </div>

            <%= yield %>
        </div>

        <%= render "common/footer" %>

    </body>
</html>

app/views/meetups/_form.html.erb
<%= simple_form_for @meetup do |f| %>
  <div class="form-group">
    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.input :description, input_html: { class: "form-control"} %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
<% end %>

app/views/meetups/edit.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>编辑meetup</h2>

    <hr>
    <%= render "form" %>

</div>

app/views/meetups/index.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("New meetup", new_meetup_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>Title</td>
        <td>Creator </td>
      </tr>
    </thead>
    <tbody>
      <% @meetups.each do |meetup| %>
        <tr>
          <td>#</td>
          <td><%= link_to(meetup.title, meetup_path(meetup)) %></td>
          <td> <%= meetup.user.email %> </td>
          <td>
            <% if current_user && current_user == meetup.user %>
                <%= link_to("Edit", edit_meetup_path(meetup), class: "btn btn-sm btn-default")%>
                <%= link_to("Delete", meetup_path(meetup),    class: "btn btn-sm btn-default",
                            method: :delete, data: { confirm: "Are you sure?" } )%>
            <% end %>

          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/meetups/new.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>新增meetup</h2>

    <hr>
    <%= render "form" %>

</div>

app/views/meetups/show.html.erb
  <div class="group">
      <% if current_user && current_user == @meetup.user %>
        <%= link_to("Edit", edit_meetup_path(@meetup), class: "btn btn-primary pull-right")%>
      <% end %>
  </div>

<h1><%= @meetup.title %></h1>
<hr><br>
<p><%= simple_format(@meetup.description) %></p>
<hr><br>

<div>
  <% if @meetup.comments.empty? %>
     <p> 尚未有人留言 </p>
   <% else %>
     <% @floor = 1 %>
     <% @meetup.comments.each do |comment| %>
       <%= @floor %>樓
       <div class="col-md-12">
         <p><%= comment.message %></p>
       </div>
       <% @floor = @floor + 1 %>
       </br>
     <% end%>
   <% end %>
   <hr>
 </div>

 <%= render 'comments/comment_form' %>

app/views/welcome/index.html.erb
<h1>Hello Hello !!</h1>